language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.4
  - 1.5
  - nightly

env:
  - PYTHON=""

jobs:
  allow_failures:
    - os: osx
    - os: windows
    - julia: nightly
  fast_finish: true

notifications:
  email: false

codecov: true
coveralls: true

script:
  - julia --project --color=yes -e 'using Pkg; Pkg.add(name="ElectromagneticFields", rev="master"); Pkg.build(verbose=true); Pkg.precompile()';
  - julia --project --color=yes -e 'using Pkg; Pkg.test(coverage=true)';
