language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.4
  - 1.5
  - nightly

env:
  - PYTHON=""

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

codecov: true
coveralls: true

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - travis_wait 50 julia --project -e 'using Pkg; Pkg.build()';
  - travis_wait 50 julia --project -e 'using Pkg; Pkg.precompile()';
  - travis_wait 50 julia --project -e 'using Pkg; Pkg.test(; coverage=true)';
